fix: Update run-tests.yml

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -1,6 +1,3 @@
-# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
-# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages
-
 name: Acceptance Tests
 
 on:
@@ -9,18 +6,30 @@ on:
       - main
       - master
 
-# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
+env:
+  NODE_VERSION: 22
+
 permissions:
   contents: read
   pages: write
   id-token: write
 
-# Allow one concurrent deployment
 concurrency:
   group: 'pages'
   cancel-in-progress: true
 
 jobs:
+  lint-check:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version: ${{ env.NODE_VERSION }}
+          registry-url: https://registry.npmjs.org/
+      - run: npm i
+      - run: npm run lint
+
   acceptance-tests:
     environment:
       name: github-pages
@@ -30,19 +39,31 @@ jobs:
       - uses: actions/checkout@v3
       - uses: actions/setup-node@v3
         with:
-          node-version: 18
+          node-version: ${{ env.NODE_VERSION }}
           registry-url: https://registry.npmjs.org/
-      - name: Run tests
+      - name: install deps
         run: |
           npm i
+      - name: Run tests
+        working-directory: ./test
+        run: |
+          npm i && npx playwright install
           npm run test && npm run allure-reports-generate && npm run allure-reports-patch
+        env:
+          MAILINATOR_TOKEN: ${{secrets.MAILINATOR_TOKEN}}
+          MAILINATOR_DOMAIN: ${{secrets.MAILINATOR_DOMAIN}}
       - name: Setup Pages
         uses: actions/configure-pages@v3
+      - name: Check artifact directory
+        run: |
+          if [ ! -d "./test/output/allure" ]; then
+            echo "Artifact directory not found. Exiting."
+            exit 1
+          fi
       - name: Upload artifact
-        uses: actions/upload-pages-artifact@v1
+        uses: actions/upload-pages-artifact@v3
         with:
-          # Upload repository
-          path: './output/allure'
+          path: './test/output/allure'
       - name: Deploy to GitHub Pages
         id: deployment
-        uses: actions/deploy-pages@v1
+        uses: actions/deploy-pages@v4
